[phases.setup]
nixPkgs = ["nodejs","npm"]

[start]
cmd = "node backend/index.js"

[variables]
NODE_VERSION = "18"

[phases.install]
cmds = [
  "cd backend",
  "npm install"
]
[phases.build]
cmds = []
